PORT = "COM3"
BAUDRATE = 9600
CAMERA_ID = 1

YOLO_WEIGHTS = "yolov8n.pt"
YOLO_TRACKER = "bytetrack.yaml"
YOLO_CONF = 0.25
YOLO_CLASSES = [0]

SAM_WEIGHTS = "sam2_t.pt"
ENABLE_SAM = True
SAM_INTERVAL = 8

YOLO_IMGSZ = 640

REID_EMBED_SIZE = 576
REID_UPPER_BODY_RATIO = 0.55
REID_SIM_THRESHOLD = 0.85
REID_REACQUIRE_THRESHOLD = 0.88
REID_ANCHOR_MIN_SIM = 0.82
REID_MATCH_MARGIN = 0.12
REID_LOCK_VERIFY_THRESHOLD = 0.80
REID_LOCK_VERIFY_INTERVAL = 5
REID_LOCK_MISMATCH_MAX = 4
REID_PICK_IOU_MIN = 0.25
REID_GALLERY_MAX = 8
REID_UPDATE_INTERVAL = 15
REID_GALLERY_MIN_DIST = 0.10
REID_GALLERY_MIN_SIM = 0.85
LOST_REID_INTERVAL = 2
REACQUIRE_SPATIAL_BASE_PX = 180
REACQUIRE_SPATIAL_EXPAND_PX = 8

FOV_DEG_H = 60.0
FOV_DEG_V = 45.0
ANGLE_CMD_SCALE = 1.0
MIN_MOVE_PX = 6
MIN_CMD_DEG = 1
MAX_CMD_DEG = 5
H_SIGN = -1
V_SIGN = -1

SERVO_MIN_ANGLE = 0
SERVO_MAX_ANGLE = 130
SERVO_INIT_H = 0
SERVO_INIT_V = 0

FIRE_RADIUS_PX = 18
STABLE_FRAMES_TO_FIRE = 8

SMOOTH_ALPHA = 0.35

LASER_MIN_AREA = 4
LASER_MAX_AREA = 600
LASER_SMOOTH_ALPHA = 0.45
LASER_HOLD_FRAMES = 45

# cpu | cuda (NVIDIA only) | intel:gpu | intel:cpu | intel:npu
DEVICE = "intel:gpu"
