PORT = "COM3"
BAUDRATE = 9600
CAMERA_ID = 1

YOLO_WEIGHTS = "yolov8n.pt"
YOLO_TRACKER = "bytetrack.yaml"
YOLO_CONF = 0.25

SAM_WEIGHTS = "sam2_t.pt"
ENABLE_SAM = False
SAM_INTERVAL = 8

YOLO_IMGSZ = 640

REID_EMBED_SIZE = 576
REID_SIM_THRESHOLD = 0.85
REID_REACQUIRE_THRESHOLD = 0.80
REID_ANCHOR_MIN_SIM = 0.70
REID_MATCH_MARGIN = 0.06
REID_GALLERY_MAX = 6
REID_UPDATE_INTERVAL = 20
REID_GALLERY_MIN_DIST = 0.10
REID_GALLERY_MIN_SIM = 0.82
LOST_REID_INTERVAL = 3
REACQUIRE_SPATIAL_BASE_PX = 180
REACQUIRE_SPATIAL_EXPAND_PX = 8

FOV_DEG_H = 60.0
FOV_DEG_V = 45.0
ANGLE_CMD_SCALE = 0.35

FIRE_RADIUS_PX = 18
STABLE_FRAMES_TO_FIRE = 8

SMOOTH_ALPHA = 0.35

# cpu | cuda (NVIDIA only) | intel:gpu | intel:cpu | intel:npu
DEVICE = "intel:gpu"
